### ISSUE TITLE
Allow bcl2fastq rule and rest of pipeline to handle samples without any reads

### ISSUE THREAD

**Issue by genomics-kl** [vari-bbc/demultiplex#6]
For certain protocols, certain samples may end up not having any reads at all assigned to it by bcl2fastq. In these cases, no output fastq file will be produced for these samples. Because the bcl2fastq rule assumes there will be fastq files output for each sample in the sample sheet, the rule will error out due to missing output files. This causes Snakemake to delete all the fastq files because it thinks that the bcl2fastq run has errored out.

Potential solution: In the bcl2fastq rule, after bcl2fastq is run, `touch` all the output files. The timestamp will be changed for the existing files while empty files will be created for each missing sample.

Complications to consider/address: 
1. This bypasses one of the main ways how Snakemake ensures that each step of the pipeline runs correctly. What about cases where there are missing output files due to actual errors in bcl2fastq?
2. I tested both FastQC and FastqScreen on empty files. FastQC errors out. FastqScreen does not error out but does not produce any output file. This means that the FastQC and FastqScreen input directives must be rewritten to use only the non-empty fastq files. I think this necessitates the use of the 'checkpoint' feature of Snakemake which allows the pipeline to determine certain parameters 'on-the-fly' based on the output of certain rules as opposed to from the beginning based on user-provided information.

**Comment by genomics-kl** [comment]
While this is being resolved, I have suggested to Marc to use the legacy (Ian's) pipeline for projects likely to produce empty samples. My understanding is that most projects do not have this issue.

**Comment by ianbed** [comment]
What about instead of 'touch', something like this

`if config["override_missing_samples"]:
    if [ ! -f {output.read1} ] && [! -f {output.read2} ]; then
           cp bin/fake_fastq1_with_10_reads.fq.gz {output.read1}
           cp bin/fake_fastq2_with_10_reads.fq.gz {output.read2}
    fi
`

This would (basically) implement your touch solution but would still allow FastQC and FastqScreen to work. Also, as you suggested, having it as an option in the config would avoid your first consideration (because it would still fail if this wasn't expected). Then it could just be easily restarted after changing the config. It would be easy enough to just check which samples have 10 reads and therefore failed (or maybe make these yeast reads and then it can be seen in the preseq or something)

**Comment by genomics-kl** [comment]
@ianbed, yes I think I like the idea of the fake reads to allow the sample names to show up in the multiQC.
